name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
        channel: 'stable'
    - run: flutter --version
    - run: cd widget_driver_annotations
    - run: flutter pub get
    - run: flutter test