targets:
  $default:
    builders:
      widget_driver_generator:
        options:
          defaultTestValues:
            "bool": "true"
            "Color": "Colors.yellow"
            "int": "123"
            "Coffee": "const Coffee(\n    name: 'Coffee',\n    description: 'Some desc',\n    imageUrl: 'http://www.exampleImage.com/image',\n  )"
            "String": "'Hello World'"