name: example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  widget_driver: ^1.0.9
  meta: ^1.7.0
  get_it: ^7.2.0
  provider: ^6.0.4
  cached_network_image: ^3.0.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^1.0.4
  widget_driver_test:
    path: ../../widget_driver_test
  build_runner:
  widget_driver_generator: ^1.2.0

flutter:
  uses-material-design: true
