name: widget_driver_annotation
description: Defines the annotations used by widget_driver and widget_driver_generator to create code for your WidgetDrivers
version: 0.0.4
repository: https://github.com/bmw-tech/widget_driver/tree/master/widget_driver_annotation
issue_tracker: https://github.com/bmw-tech/widget_driver/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  test: ^1.22.2
