builders:
  widget_driver_generator:
    import: "package:widget_driver_generator/builder.dart"
    builder_factories: ["generateWidgetDriver"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
