name: widget_driver_generator
description: This package provides generators for WidgetDriver to automate the creation of your TestDrivers and WidgetDriverProviders
version: 1.0.1
repository: https://github.com/bmw-tech/widget_driver/tree/master/widget_driver_generator
issue_tracker: https://github.com/bmw-tech/widget_driver/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^4.7.0
  widget_driver_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^2.0.1
  test: ^1.22.2
  mocktail: ^0.1.4
