name: widget_driver_generator
description: Generator for WidgetDriver
version: 0.0.1
repository: https://github.com/bmw-tech/widget_driver/tree/master/widget_driver_generator
issue_tracker: https://github.com/bmw-tech/widget_driver/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  build: 
  source_gen:
  widget_driver_annotation:
    path: ../widget_driver_annotation/

dev_dependencies:
  build_runner:
  build_test:
  test: ^1.16.0