name: widget_driver_generator
description: This package provides generators for WidgetDriver to automate the creation of your TestDrivers and WidgetDriverProviders
version: 0.0.4
repository: https://github.com/bmw-tech/widget_driver/tree/master/widget_driver_generator
issue_tracker: https://github.com/bmw-tech/widget_driver/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  build:
  source_gen:
  analyzer:
  widget_driver_annotation: ^0.0.4

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.1
  test: ^1.22.2
