name: widget_driver_test
description: Contains helper classes/methods for DrivableWidgets, WidgetDrivers, helps with TestDrivers mocking
version: 0.0.4
repository: https://github.com/bmw-tech/widget_driver/tree/master/widget_driver_test
issue_tracker: https://github.com/bmw-tech/widget_driver/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widget_driver: ^0.0.6
  mocktail: ^0.1.4
  meta: ^1.7.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
