name: check-code-quality
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Fail if pipeline label was not set
        if: ${{ github.event.label.name != 'ready for pipeline' }}
        run: |
          echo "please set the label 'ready for pipeline' to start the pipeline"
          failure()
      - name: Checkout the latest code
        uses: actions/checkout@v2
      - name: prepare flutter
        uses: subosito/flutter-action@v2
          with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - name: Run quality checks if pipeline label was set
        run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.3.4-x64
          make quality