name: test-my-app
on: [workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Flutter version
      run: flutter --version
    - name: Test widget_driver_annotation
      run: |
        cd widget_driver_annotation
        flutter pub get 
        flutter test
